name: cat_inspector
description: CAT 950-982 Wheel Loader Inspection Assistant
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  image_picker: ^1.1.2
  camera: ^0.11.0+2

dev_dependencies:
  lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/982.png
    - assets/components.json

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/loader2.png"
